### ISSUE TITLE
React warnings when running in development mode from npm package

### ISSUE THREAD

**Issue by adamsilverstein** [Dayjo/react-character-map#1]
When using this component in my project I noticed console warnings:

`Warning: Each child in an array or iterator should have a unique "key" prop`

I was able to correct this in the dist version of the code by adding unique keys to iterated elements, I'll open a PR here with those fixes.

**Comment by adamsilverstein** [comment]
Aha: looking at the repository source code, I see you have added some random keys (eg https://github.com/Dayjo/react-character-map/blob/master/src/component/CharacterMap.js#L42). It doesn't look like this change is in the version shipped to npm.  Can that get updated?

Also, best practice usually recommends against random keys since React will need to re-render unchanged components more frequently. probably not a huge concern, however using the iterator to make a unique but predictable key would eliminate that issue.

**Comment by Dayjo** [comment]
Hi Adam,

Thanks so much for your contribution! I have merged and published the new version 👍

**Comment by adamsilverstein** [comment]
Excellent, thank you @Dayjo!
