### ISSUE TITLE
Unique class and improper `aria-label` for filter `ul`

### ISSUE THREAD

**Issue by helen** [Dayjo/react-character-map#13]
For @adamsilverstein:

As I was working on styling this component in our plugin, I noticed in the generated HTML that the `ul` containing the filter has the `charMap--category-menu` class and an `aria-label` of `Categories`, whereas the actual `ul` for the list of categories gets the same class but does not get the `aria-label`. So two things:

* The `aria-label` needs to be assigned to the correct element
* The filter `ul` should get a different class to be correct and for targeting - perhaps `charMap--filter`

**Comment by adamsilverstein** [comment]
@helen thanks for catching that - I'll work on a PR to correct. I think these got duplicated when resolving conflicts between several previous PRs.

**Comment by adamsilverstein** [comment]
> I noticed in the generated HTML that the ul containing the filter has the charMap--category-menu class and an aria-label of Categories

@helen - Looks like some of this is already improved here (my fork is out of date) 

I added the suggested class in https://github.com/Dayjo/react-character-map/pull/14

I notice we have an aria-label on the input filter element, does that seem right (vs being on the ul)?

**Comment by Dayjo** [comment]
#14  has now been merged in. Feel free to add further suggestions for accessibility, I'm keen to make it as accessible as possible.

**Comment by adamsilverstein** [comment]
> Feel free to add further suggestions for accessibility, I'm keen to make it as accessible as possible.

Excellent, hoping to get some help reviewing with a more experienced colleague

**Comment by Dayjo** [comment]
Great. I'll close this one for now as the specific example was covered in #14.
