### ISSUE TITLE
Allow text to be passed as props (for i18n)

### ISSUE THREAD

**Issue by johnwatkins0** [Dayjo/react-character-map#15]
This is in reference to 10up's Insert Special Characters WordPress plugin. [This issue regarding improvement to the plugin's translation support](https://github.com/10up/insert-special-characters/issues/51) mentions there are a few pieces of text in this package that are not currently translatable. 

I think the solution for this would be to provide defaults in this component (the current text) that can be overridden via props. Then we can pass the props in from downstream, and this repo wouldn't have to implement its own translation. 

I'm aiming to submit a PR in the next 1-2 days, unless you would prefer to handle it, @Dayjo.

**Comment by Dayjo** [comment]
Sounds like a very sensible plan @johnwatkins0  :) Go ahead, I'll keep an eye out for it 👍
