### ISSUE TITLE
Is the library still in maintenance ?

### ISSUE THREAD

**Issue by franjorub** [Dayjo/react-character-map#19]
Hi, greetings, I like this library is usefully for a feature that I'm working, but maybe I want upgrade a bit the component, with hooks and more custom properties for the classnames or disable the search bar and only leave the categories list, are you interested in those changes if I send a pr soon ? :)

**Comment by Dayjo** [comment]
Hi @franjorub,

Yes, the package is still accepting pull requests and issue reports. https://github.com/10up/insert-special-characters is using it for their Wordpress plugin and so some form of maintenance is ongoing, they also have a list of potentially useful changes (the default charsets grouping etc) that are in need of assistance, it might be worth noting if the changes you're looking to do cover any of those issues.

Feel few to discuss changes you want here too.
