### ISSUE TITLE
Consider a search feature

### ISSUE THREAD

**Issue by adamsilverstein** [Dayjo/react-character-map#4]
**Overview.**
The character map order is mostly ASCII-related but doesn't really make a lot of human sense, and there are a _lot_ of characters. Making it searchable would enhance usability.

**Describe the solution you'd like**
Search input that filters on a basic string search that matches from the beginning of string (want to be able to search for `a` without it matching almost everything, for instance)

**Comment by Dayjo** [comment]
Search has been implemented in the latest release `v0.2.0`
