### ISSUE TITLE
Improve Accessibility

### ISSUE THREAD

**Issue by adamsilverstein** [Dayjo/react-character-map#7]
When using this component I noticed a couple of accessibility issues we can fix. In addition it would be useful to get a more expert accessibility review.

#### Unable to tab past the categories
When focusing on the component, I am unable to tab past selecting the categories: I have to use my mouse.
#### Use of `a href` links should be for navigation, these elements should be buttons
![](https://cl.ly/84a14fb5a20c/Screen%252520Recording%2525202019-08-09%252520at%25252004.55%252520PM.gif)

**Comment by Dayjo** [comment]
Thanks for your help, we have merged in and released these changes
